export const API_ENDPOINTS = {
  backend: {
    clients: "/clients",
    dashboard: "/dashboard",
    login: "/internal/login",
    logout: "/internal/logout",
    me: "/internal/me",
    deposits: "/deposits",
    investmentPlans: "/investment-plans",
    paymentMethods: "/payment-methods",
    refresh: "/internal/token/refresh",
    transactions: "/transactions",
    withdrawals: "/withdrawals",
  },
  frontend: {
    clients: "/api/admin/clients",
    dashboard: "/api/admin/dashboard",
    login: "/api/admin/login",
    logout: "/api/admin/logout",
    deposits: "/api/admin/deposits",
    investmentPlans: "/api/admin/investment-plans",
    paymentMethods: "/api/admin/payment-methods",
    refresh: "/api/admin/token/refresh",
    transactions: "/api/admin/transactions",
    withdrawals: "/api/admin/withdrawals",
  },
} as const;
